- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: whoami
      shell: whoami
      become: yes


    - name: get artifact
      get_url:
        url: http://art.nimbus.beescloud.com:80/artifactory/thirdparty/gwt-servlet/gwt-servlet/2.5.0/gwt-servlet-2.5.0-ec1.jar
        dest: /tmp/file.jar
